<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\District;
use App\Models\Thana;
use Str;

class ThanaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $upazilas = array(
            array('district_slug' => 'comilla', 'name' => 'Debidwar', 'name_bn' => 'দেবিদ্বার', 'url' => 'debidwar.comilla.gov.bd'),
            array('district_slug' => 'comilla', 'name' => 'Barura', 'name_bn' => 'বরুড়া', 'url' => 'barura.comilla.gov.bd'),
            array('district_slug' => 'comilla', 'name' => 'Brahmanpara', 'name_bn' => 'ব্রাহ্মণপাড়া', 'url' => 'brahmanpara.comilla.gov.bd'),
            array('district_slug' => 'comilla', 'name' => 'Chandina', 'name_bn' => 'চান্দিনা', 'url' => 'chandina.comilla.gov.bd'),
            array('district_slug' => 'comilla', 'name' => 'Chauddagram', 'name_bn' => 'চৌদ্দগ্রাম', 'url' => 'chauddagram.comilla.gov.bd'),
            array('district_slug' => 'comilla', 'name' => 'Daudkandi', 'name_bn' => 'দাউদকান্দি', 'url' => 'daudkandi.comilla.gov.bd'),
            array('district_slug' => 'comilla', 'name' => 'Homna', 'name_bn' => 'হোমনা', 'url' => 'homna.comilla.gov.bd'),
            array('district_slug' => 'comilla', 'name' => 'Laksam', 'name_bn' => 'লাকসাম', 'url' => 'laksam.comilla.gov.bd'),
            array('district_slug' => 'comilla', 'name' => 'Muradnagar', 'name_bn' => 'মুরাদনগর', 'url' => 'muradnagar.comilla.gov.bd'),
            array('district_slug' => 'comilla', 'name' => 'Nangalkot', 'name_bn' => 'নাঙ্গলকোট', 'url' => 'nangalkot.comilla.gov.bd'),
            array('district_slug' => 'comilla', 'name' => 'Comilla Sadar', 'name_bn' => 'কুমিল্লা সদর', 'url' => 'comillasadar.comilla.gov.bd'),
            array('district_slug' => 'comilla', 'name' => 'Meghna', 'name_bn' => 'মেঘনা', 'url' => 'meghna.comilla.gov.bd'),
            array('district_slug' => 'comilla', 'name' => 'Monohargonj', 'name_bn' => 'মনোহরগঞ্জ', 'url' => 'monohargonj.comilla.gov.bd'),
            array('district_slug' => 'comilla', 'name' => 'Sadarsouth', 'name_bn' => 'সদর দক্ষিণ', 'url' => 'sadarsouth.comilla.gov.bd'),
            array('district_slug' => 'comilla', 'name' => 'Titas', 'name_bn' => 'তিতাস', 'url' => 'titas.comilla.gov.bd'),
            array('district_slug' => 'comilla', 'name' => 'Burichang', 'name_bn' => 'বুড়িচং', 'url' => 'burichang.comilla.gov.bd'),
            array('district_slug' => 'comilla', 'name' => 'Lalmai', 'name_bn' => 'লালমাই', 'url' => 'lalmai.comilla.gov.bd'),
            array('district_slug' => 'feni', 'name' => 'Chhagalnaiya', 'name_bn' => 'ছাগলনাইয়া', 'url' => 'chhagalnaiya.feni.gov.bd'),
            array('district_slug' => 'feni', 'name' => 'Feni Sadar', 'name_bn' => 'ফেনী সদর', 'url' => 'sadar.feni.gov.bd'),
            array('district_slug' => 'feni', 'name' => 'Sonagazi', 'name_bn' => 'সোনাগাজী', 'url' => 'sonagazi.feni.gov.bd'),
            array('district_slug' => 'feni', 'name' => 'Fulgazi', 'name_bn' => 'ফুলগাজী', 'url' => 'fulgazi.feni.gov.bd'),
            array('district_slug' => 'feni', 'name' => 'Parshuram', 'name_bn' => 'পরশুরাম', 'url' => 'parshuram.feni.gov.bd'),
            array('district_slug' => 'feni', 'name' => 'Daganbhuiyan', 'name_bn' => 'দাগনভূঞা', 'url' => 'daganbhuiyan.feni.gov.bd'),
            array('district_slug' => 'brahmanbaria', 'name' => 'Brahmanbaria Sadar', 'name_bn' => 'ব্রাহ্মণবাড়িয়া সদর', 'url' => 'sadar.brahmanbaria.gov.bd'),
            array('district_slug' => 'brahmanbaria', 'name' => 'Kasba', 'name_bn' => 'কসবা', 'url' => 'kasba.brahmanbaria.gov.bd'),
            array('district_slug' => 'brahmanbaria', 'name' => 'Nasirnagar', 'name_bn' => 'নাসিরনগর', 'url' => 'nasirnagar.brahmanbaria.gov.bd'),
            array('district_slug' => 'brahmanbaria', 'name' => 'Sarail', 'name_bn' => 'সরাইল', 'url' => 'sarail.brahmanbaria.gov.bd'),
            array('district_slug' => 'brahmanbaria', 'name' => 'Ashuganj', 'name_bn' => 'আশুগঞ্জ', 'url' => 'ashuganj.brahmanbaria.gov.bd'),
            array('district_slug' => 'brahmanbaria', 'name' => 'Akhaura', 'name_bn' => 'আখাউড়া', 'url' => 'akhaura.brahmanbaria.gov.bd'),
            array('district_slug' => 'brahmanbaria', 'name' => 'Nabinagar', 'name_bn' => 'নবীনগর', 'url' => 'nabinagar.brahmanbaria.gov.bd'),
            array('district_slug' => 'brahmanbaria', 'name' => 'Bancharampur', 'name_bn' => 'বাঞ্ছারামপুর', 'url' => 'bancharampur.brahmanbaria.gov.bd'),
            array('district_slug' => 'brahmanbaria', 'name' => 'Bijoynagar', 'name_bn' => 'বিজয়নগর', 'url' => 'bijoynagar.brahmanbaria.gov.bd    '),
            array('district_slug' => 'rangamati', 'name' => 'Rangamati Sadar', 'name_bn' => 'রাঙ্গামাটি সদর', 'url' => 'sadar.rangamati.gov.bd'),
            array('district_slug' => 'rangamati', 'name' => 'Kaptai', 'name_bn' => 'কাপ্তাই', 'url' => 'kaptai.rangamati.gov.bd'),
            array('district_slug' => 'rangamati', 'name' => 'Kawkhali', 'name_bn' => 'কাউখালী', 'url' => 'kawkhali.rangamati.gov.bd'),
            array('district_slug' => 'rangamati', 'name' => 'Baghaichari', 'name_bn' => 'বাঘাইছড়ি', 'url' => 'baghaichari.rangamati.gov.bd'),
            array('district_slug' => 'rangamati', 'name' => 'Barkal', 'name_bn' => 'বরকল', 'url' => 'barkal.rangamati.gov.bd'),
            array('district_slug' => 'rangamati', 'name' => 'Langadu', 'name_bn' => 'লংগদু', 'url' => 'langadu.rangamati.gov.bd'),
            array('district_slug' => 'rangamati', 'name' => 'Rajasthali', 'name_bn' => 'রাজস্থলী', 'url' => 'rajasthali.rangamati.gov.bd'),
            array('district_slug' => 'rangamati', 'name' => 'Belaichari', 'name_bn' => 'বিলাইছড়ি', 'url' => 'belaichari.rangamati.gov.bd'),
            array('district_slug' => 'rangamati', 'name' => 'Juraichari', 'name_bn' => 'জুরাছড়ি', 'url' => 'juraichari.rangamati.gov.bd'),
            array('district_slug' => 'rangamati', 'name' => 'Naniarchar', 'name_bn' => 'নানিয়ারচর', 'url' => 'naniarchar.rangamati.gov.bd'),
            array('district_slug' => 'noakhali', 'name' => 'Noakhali Sadar', 'name_bn' => 'নোয়াখালী সদর', 'url' => 'sadar.noakhali.gov.bd'),
            array('district_slug' => 'noakhali', 'name' => 'Companiganj', 'name_bn' => 'কোম্পানীগঞ্জ', 'url' => 'companiganj.noakhali.gov.bd'),
            array('district_slug' => 'noakhali', 'name' => 'Begumganj', 'name_bn' => 'বেগমগঞ্জ', 'url' => 'begumganj.noakhali.gov.bd'),
            array('district_slug' => 'noakhali', 'name' => 'Hatia', 'name_bn' => 'হাতিয়া', 'url' => 'hatia.noakhali.gov.bd'),
            array('district_slug' => 'noakhali', 'name' => 'Subarnachar', 'name_bn' => 'সুবর্ণচর', 'url' => 'subarnachar.noakhali.gov.bd'),
            array('district_slug' => 'noakhali', 'name' => 'Kabirhat', 'name_bn' => 'কবিরহাট', 'url' => 'kabirhat.noakhali.gov.bd'),
            array('district_slug' => 'noakhali', 'name' => 'Senbug', 'name_bn' => 'সেনবাগ', 'url' => 'senbug.noakhali.gov.bd'),
            array('district_slug' => 'noakhali', 'name' => 'Chatkhil', 'name_bn' => 'চাটখিল', 'url' => 'chatkhil.noakhali.gov.bd'),
            array('district_slug' => 'noakhali', 'name' => 'Sonaimori', 'name_bn' => 'সোনাইমুড়ী', 'url' => 'sonaimori.noakhali.gov.bd'),
            array('district_slug' => 'chandpur', 'name' => 'Haimchar', 'name_bn' => 'হাইমচর', 'url' => 'haimchar.chandpur.gov.bd'),
            array('district_slug' => 'chandpur', 'name' => 'Kachua', 'name_bn' => 'কচুয়া', 'url' => 'kachua.chandpur.gov.bd'),
            array('district_slug' => 'chandpur', 'name' => 'Shahrasti', 'name_bn' => 'শাহরাস্তি	', 'url' => 'shahrasti.chandpur.gov.bd'),
            array('district_slug' => 'chandpur', 'name' => 'Chandpur Sadar', 'name_bn' => 'চাঁদপুর সদর', 'url' => 'sadar.chandpur.gov.bd'),
            array('district_slug' => 'chandpur', 'name' => 'Matlab South', 'name_bn' => 'মতলব দক্ষিণ', 'url' => 'matlabsouth.chandpur.gov.bd'),
            array('district_slug' => 'chandpur', 'name' => 'Hajiganj', 'name_bn' => 'হাজীগঞ্জ', 'url' => 'hajiganj.chandpur.gov.bd'),
            array('district_slug' => 'chandpur', 'name' => 'Matlab North', 'name_bn' => 'মতলব উত্তর', 'url' => 'matlabnorth.chandpur.gov.bd'),
            array('district_slug' => 'chandpur', 'name' => 'Faridgonj', 'name_bn' => 'ফরিদগঞ্জ', 'url' => 'faridgonj.chandpur.gov.bd'),
            array('district_slug' => 'lakshmipur', 'name' => 'Lakshmipur Sadar', 'name_bn' => 'লক্ষ্মীপুর সদর', 'url' => 'sadar.lakshmipur.gov.bd'),
            array('district_slug' => 'lakshmipur', 'name' => 'Kamalnagar', 'name_bn' => 'কমলনগর', 'url' => 'kamalnagar.lakshmipur.gov.bd'),
            array('district_slug' => 'lakshmipur', 'name' => 'Raipur', 'name_bn' => 'রায়পুর', 'url' => 'raipur.lakshmipur.gov.bd'),
            array('district_slug' => 'lakshmipur', 'name' => 'Ramgati', 'name_bn' => 'রামগতি', 'url' => 'ramgati.lakshmipur.gov.bd'),
            array('district_slug' => 'lakshmipur', 'name' => 'Ramganj', 'name_bn' => 'রামগঞ্জ', 'url' => 'ramganj.lakshmipur.gov.bd'),
            array('district_slug' => 'chattogram', 'name' => 'Rangunia', 'name_bn' => 'রাঙ্গুনিয়া', 'url' => 'rangunia.chittagong.gov.bd'),
            array('district_slug' => 'chattogram', 'name' => 'Sitakunda', 'name_bn' => 'সীতাকুন্ড', 'url' => 'sitakunda.chittagong.gov.bd'),
            array('district_slug' => 'chattogram', 'name' => 'Mirsharai', 'name_bn' => 'মীরসরাই', 'url' => 'mirsharai.chittagong.gov.bd'),
            array('district_slug' => 'chattogram', 'name' => 'Patiya', 'name_bn' => 'পটিয়া', 'url' => 'patiya.chittagong.gov.bd'),
            array('district_slug' => 'chattogram', 'name' => 'Sandwip', 'name_bn' => 'সন্দ্বীপ', 'url' => 'sandwip.chittagong.gov.bd'),
            array('district_slug' => 'chattogram', 'name' => 'Banshkhali', 'name_bn' => 'বাঁশখালী', 'url' => 'banshkhali.chittagong.gov.bd'),
            array('district_slug' => 'chattogram', 'name' => 'Boalkhali', 'name_bn' => 'বোয়ালখালী', 'url' => 'boalkhali.chittagong.gov.bd'),
            array('district_slug' => 'chattogram', 'name' => 'Anwara', 'name_bn' => 'আনোয়ারা', 'url' => 'anwara.chittagong.gov.bd'),
            array('district_slug' => 'chattogram', 'name' => 'Chandanaish', 'name_bn' => 'চন্দনাইশ', 'url' => 'chandanaish.chittagong.gov.bd'),
            array('district_slug' => 'chattogram', 'name' => 'Satkania', 'name_bn' => 'সাতকানিয়া', 'url' => 'satkania.chittagong.gov.bd'),
            array('district_slug' => 'chattogram', 'name' => 'Lohagara', 'name_bn' => 'লোহাগাড়া', 'url' => 'lohagara.chittagong.gov.bd'),
            array('district_slug' => 'chattogram', 'name' => 'Hathazari', 'name_bn' => 'হাটহাজারী', 'url' => 'hathazari.chittagong.gov.bd'),
            array('district_slug' => 'chattogram', 'name' => 'Fatikchhari', 'name_bn' => 'ফটিকছড়ি', 'url' => 'fatikchhari.chittagong.gov.bd'),
            array('district_slug' => 'chattogram', 'name' => 'Raozan', 'name_bn' => 'রাউজান', 'url' => 'raozan.chittagong.gov.bd'),
            array('district_slug' => 'chattogram', 'name' => 'Karnafuli', 'name_bn' => 'কর্ণফুলী', 'url' => 'karnafuli.chittagong.gov.bd'),
            array('district_slug' => 'coxsbazar', 'name' => 'Coxsbazar Sadar', 'name_bn' => 'কক্সবাজার সদর', 'url' => 'sadar.coxsbazar.gov.bd'),
            array('district_slug' => 'coxsbazar', 'name' => 'Chakaria', 'name_bn' => 'চকরিয়া', 'url' => 'chakaria.coxsbazar.gov.bd'),
            array('district_slug' => 'coxsbazar', 'name' => 'Kutubdia', 'name_bn' => 'কুতুবদিয়া', 'url' => 'kutubdia.coxsbazar.gov.bd'),
            array('district_slug' => 'coxsbazar', 'name' => 'Ukhiya', 'name_bn' => 'উখিয়া', 'url' => 'ukhiya.coxsbazar.gov.bd'),
            array('district_slug' => 'coxsbazar', 'name' => 'Moheshkhali', 'name_bn' => 'মহেশখালী', 'url' => 'moheshkhali.coxsbazar.gov.bd'),
            array('district_slug' => 'coxsbazar', 'name' => 'Pekua', 'name_bn' => 'পেকুয়া', 'url' => 'pekua.coxsbazar.gov.bd'),
            array('district_slug' => 'coxsbazar', 'name' => 'Ramu', 'name_bn' => 'রামু', 'url' => 'ramu.coxsbazar.gov.bd'),
            array('district_slug' => 'coxsbazar', 'name' => 'Teknaf', 'name_bn' => 'টেকনাফ', 'url' => 'teknaf.coxsbazar.gov.bd'),
            array('district_slug' => 'khagrachhari', 'name' => 'Khagrachhari Sadar', 'name_bn' => 'খাগড়াছড়ি সদর', 'url' => 'sadar.khagrachhari.gov.bd'),
            array('district_slug' => 'khagrachhari', 'name' => 'Dighinala', 'name_bn' => 'দিঘীনালা', 'url' => 'dighinala.khagrachhari.gov.bd'),
            array('district_slug' => 'khagrachhari', 'name' => 'Panchari', 'name_bn' => 'পানছড়ি', 'url' => 'panchari.khagrachhari.gov.bd'),
            array('district_slug' => 'khagrachhari', 'name' => 'Laxmichhari', 'name_bn' => 'লক্ষীছড়ি', 'url' => 'laxmichhari.khagrachhari.gov.bd'),
            array('district_slug' => 'khagrachhari', 'name' => 'Mohalchari', 'name_bn' => 'মহালছড়ি', 'url' => 'mohalchari.khagrachhari.gov.bd'),
            array('district_slug' => 'khagrachhari', 'name' => 'Manikchari', 'name_bn' => 'মানিকছড়ি', 'url' => 'manikchari.khagrachhari.gov.bd'),
            array('district_slug' => 'khagrachhari', 'name' => 'Ramgarh', 'name_bn' => 'রামগড়', 'url' => 'ramgarh.khagrachhari.gov.bd'),
            array('district_slug' => 'khagrachhari', 'name' => 'Matiranga', 'name_bn' => 'মাটিরাঙ্গা', 'url' => 'matiranga.khagrachhari.gov.bd'),
            array('district_slug' => 'khagrachhari', 'name' => 'Guimara', 'name_bn' => 'গুইমারা', 'url' => 'guimara.khagrachhari.gov.bd'),
            array('district_slug' => 'bandarban', 'name' => 'Bandarban Sadar', 'name_bn' => 'বান্দরবান সদর', 'url' => 'sadar.bandarban.gov.bd'),
            array('district_slug' => 'bandarban', 'name' => 'Alikadam', 'name_bn' => 'আলীকদম', 'url' => 'alikadam.bandarban.gov.bd'),
            array('district_slug' => 'bandarban', 'name' => 'Naikhongchhari', 'name_bn' => 'নাইক্ষ্যংছড়ি', 'url' => 'naikhongchhari.bandarban.gov.bd'),
            array('district_slug' => 'bandarban', 'name' => 'Rowangchhari', 'name_bn' => 'রোয়াংছড়ি', 'url' => 'rowangchhari.bandarban.gov.bd'),
            array('district_slug' => 'bandarban', 'name' => 'Lama', 'name_bn' => 'লামা', 'url' => 'lama.bandarban.gov.bd'),
            array('district_slug' => 'bandarban', 'name' => 'Ruma', 'name_bn' => 'রুমা', 'url' => 'ruma.bandarban.gov.bd'),
            array('district_slug' => 'bandarban', 'name' => 'Thanchi', 'name_bn' => 'থানচি', 'url' => 'thanchi.bandarban.gov.bd'),
            array('district_slug' => 'sirajganj', 'name' => 'Belkuchi', 'name_bn' => 'বেলকুচি', 'url' => 'belkuchi.sirajganj.gov.bd'),
            array('district_slug' => 'sirajganj', 'name' => 'Chauhali', 'name_bn' => 'চৌহালি', 'url' => 'chauhali.sirajganj.gov.bd'),
            array('district_slug' => 'sirajganj', 'name' => 'Kamarkhand', 'name_bn' => 'কামারখন্দ', 'url' => 'kamarkhand.sirajganj.gov.bd'),
            array('district_slug' => 'sirajganj', 'name' => 'Kazipur', 'name_bn' => 'কাজীপুর', 'url' => 'kazipur.sirajganj.gov.bd'),
            array('district_slug' => 'sirajganj', 'name' => 'Raigonj', 'name_bn' => 'রায়গঞ্জ', 'url' => 'raigonj.sirajganj.gov.bd'),
            array('district_slug' => 'sirajganj', 'name' => 'Shahjadpur', 'name_bn' => 'শাহজাদপুর', 'url' => 'shahjadpur.sirajganj.gov.bd'),
            array('district_slug' => 'sirajganj', 'name' => 'Sirajganj Sadar', 'name_bn' => 'সিরাজগঞ্জ সদর', 'url' => 'sirajganjsadar.sirajganj.gov.bd'),
            array('district_slug' => 'sirajganj', 'name' => 'Tarash', 'name_bn' => 'তাড়াশ', 'url' => 'tarash.sirajganj.gov.bd'),
            array('district_slug' => 'sirajganj', 'name' => 'Ullapara', 'name_bn' => 'উল্লাপাড়া', 'url' => 'ullapara.sirajganj.gov.bd'),
            array('district_slug' => 'pabna', 'name' => 'Sujanagar', 'name_bn' => 'সুজানগর', 'url' => 'sujanagar.pabna.gov.bd'),
            array('district_slug' => 'pabna', 'name' => 'Ishurdi', 'name_bn' => 'ঈশ্বরদী', 'url' => 'ishurdi.pabna.gov.bd'),
            array('district_slug' => 'pabna', 'name' => 'Bhangura', 'name_bn' => 'ভাঙ্গুড়া', 'url' => 'bhangura.pabna.gov.bd'),
            array('district_slug' => 'pabna', 'name' => 'Pabna Sadar', 'name_bn' => 'পাবনা সদর', 'url' => 'pabnasadar.pabna.gov.bd'),
            array('district_slug' => 'pabna', 'name' => 'Bera', 'name_bn' => 'বেড়া', 'url' => 'bera.pabna.gov.bd'),
            array('district_slug' => 'pabna', 'name' => 'Atghoria', 'name_bn' => 'আটঘরিয়া', 'url' => 'atghoria.pabna.gov.bd'),
            array('district_slug' => 'pabna', 'name' => 'Chatmohar', 'name_bn' => 'চাটমোহর', 'url' => 'chatmohar.pabna.gov.bd'),
            array('district_slug' => 'pabna', 'name' => 'Santhia', 'name_bn' => 'সাঁথিয়া', 'url' => 'santhia.pabna.gov.bd'),
            array('district_slug' => 'pabna', 'name' => 'Faridpur', 'name_bn' => 'ফরিদপুর', 'url' => 'faridpur.pabna.gov.bd'),
            array('district_slug' => 'bogura', 'name' => 'Kahaloo', 'name_bn' => 'কাহালু', 'url' => 'kahaloo.bogra.gov.bd'),
            array('district_slug' => 'bogura', 'name' => 'Bogra Sadar', 'name_bn' => 'বগুড়া সদর', 'url' => 'sadar.bogra.gov.bd'),
            array('district_slug' => 'bogura', 'name' => 'Shariakandi', 'name_bn' => 'সারিয়াকান্দি', 'url' => 'shariakandi.bogra.gov.bd'),
            array('district_slug' => 'bogura', 'name' => 'Shajahanpur', 'name_bn' => 'শাজাহানপুর', 'url' => 'shajahanpur.bogra.gov.bd'),
            array('district_slug' => 'bogura', 'name' => 'Dupchanchia', 'name_bn' => 'দুপচাচিঁয়া', 'url' => 'dupchanchia.bogra.gov.bd'),
            array('district_slug' => 'bogura', 'name' => 'Adamdighi', 'name_bn' => 'আদমদিঘি', 'url' => 'adamdighi.bogra.gov.bd'),
            array('district_slug' => 'bogura', 'name' => 'Nondigram', 'name_bn' => 'নন্দিগ্রাম', 'url' => 'nondigram.bogra.gov.bd'),
            array('district_slug' => 'bogura', 'name' => 'Sonatala', 'name_bn' => 'সোনাতলা', 'url' => 'sonatala.bogra.gov.bd'),
            array('district_slug' => 'bogura', 'name' => 'Dhunot', 'name_bn' => 'ধুনট', 'url' => 'dhunot.bogra.gov.bd'),
            array('district_slug' => 'bogura', 'name' => 'Gabtali', 'name_bn' => 'গাবতলী', 'url' => 'gabtali.bogra.gov.bd'),
            array('district_slug' => 'bogura', 'name' => 'Sherpur', 'name_bn' => 'শেরপুর', 'url' => 'sherpur.bogra.gov.bd'),
            array('district_slug' => 'bogura', 'name' => 'Shibganj', 'name_bn' => 'শিবগঞ্জ', 'url' => 'shibganj.bogra.gov.bd'),
            array('district_slug' => 'rajshahi', 'name' => 'Paba', 'name_bn' => 'পবা', 'url' => 'paba.rajshahi.gov.bd'),
            array('district_slug' => 'rajshahi', 'name' => 'Durgapur', 'name_bn' => 'দুর্গাপুর', 'url' => 'durgapur.rajshahi.gov.bd'),
            array('district_slug' => 'rajshahi', 'name' => 'Mohonpur', 'name_bn' => 'মোহনপুর', 'url' => 'mohonpur.rajshahi.gov.bd'),
            array('district_slug' => 'rajshahi', 'name' => 'Charghat', 'name_bn' => 'চারঘাট', 'url' => 'charghat.rajshahi.gov.bd'),
            array('district_slug' => 'rajshahi', 'name' => 'Puthia', 'name_bn' => 'পুঠিয়া', 'url' => 'puthia.rajshahi.gov.bd'),
            array('district_slug' => 'rajshahi', 'name' => 'Bagha', 'name_bn' => 'বাঘা', 'url' => 'bagha.rajshahi.gov.bd'),
            array('district_slug' => 'rajshahi', 'name' => 'Godagari', 'name_bn' => 'গোদাগাড়ী', 'url' => 'godagari.rajshahi.gov.bd'),
            array('district_slug' => 'rajshahi', 'name' => 'Tanore', 'name_bn' => 'তানোর', 'url' => 'tanore.rajshahi.gov.bd'),
            array('district_slug' => 'rajshahi', 'name' => 'Bagmara', 'name_bn' => 'বাগমারা', 'url' => 'bagmara.rajshahi.gov.bd'),
            array('district_slug' => 'natore', 'name' => 'Natore Sadar', 'name_bn' => 'নাটোর সদর', 'url' => 'natoresadar.natore.gov.bd'),
            array('district_slug' => 'natore', 'name' => 'Singra', 'name_bn' => 'সিংড়া', 'url' => 'singra.natore.gov.bd'),
            array('district_slug' => 'natore', 'name' => 'Baraigram', 'name_bn' => 'বড়াইগ্রাম', 'url' => 'baraigram.natore.gov.bd'),
            array('district_slug' => 'natore', 'name' => 'Bagatipara', 'name_bn' => 'বাগাতিপাড়া', 'url' => 'bagatipara.natore.gov.bd'),
            array('district_slug' => 'natore', 'name' => 'Lalpur', 'name_bn' => 'লালপুর', 'url' => 'lalpur.natore.gov.bd'),
            array('district_slug' => 'natore', 'name' => 'Gurudaspur', 'name_bn' => 'গুরুদাসপুর', 'url' => 'gurudaspur.natore.gov.bd'),
            array('district_slug' => 'natore', 'name' => 'Naldanga', 'name_bn' => 'নলডাঙ্গা', 'url' => 'naldanga.natore.gov.bd'),
            array('district_slug' => 'joypurhat', 'name' => 'Akkelpur', 'name_bn' => 'আক্কেলপুর', 'url' => 'akkelpur.joypurhat.gov.bd'),
            array('district_slug' => 'joypurhat', 'name' => 'Kalai', 'name_bn' => 'কালাই', 'url' => 'kalai.joypurhat.gov.bd'),
            array('district_slug' => 'joypurhat', 'name' => 'Khetlal', 'name_bn' => 'ক্ষেতলাল', 'url' => 'khetlal.joypurhat.gov.bd'),
            array('district_slug' => 'joypurhat', 'name' => 'Panchbibi', 'name_bn' => 'পাঁচবিবি', 'url' => 'panchbibi.joypurhat.gov.bd'),
            array('district_slug' => 'joypurhat', 'name' => 'Joypurhat Sadar', 'name_bn' => 'জয়পুরহাট সদর', 'url' => 'joypurhatsadar.joypurhat.gov.bd'),
            array('district_slug' => 'chapainawabganj', 'name' => 'Chapainawabganj Sadar', 'name_bn' => 'চাঁপাইনবাবগঞ্জ সদর', 'url' => 'chapainawabganjsadar.chapainawabganj.gov.bd'),
            array('district_slug' => 'chapainawabganj', 'name' => 'Gomostapur', 'name_bn' => 'গোমস্তাপুর', 'url' => 'gomostapur.chapainawabganj.gov.bd'),
            array('district_slug' => 'chapainawabganj', 'name' => 'Nachol', 'name_bn' => 'নাচোল', 'url' => 'nachol.chapainawabganj.gov.bd'),
            array('district_slug' => 'chapainawabganj', 'name' => 'Bholahat', 'name_bn' => 'ভোলাহাট', 'url' => 'bholahat.chapainawabganj.gov.bd'),
            array('district_slug' => 'chapainawabganj', 'name' => 'Shibganj', 'name_bn' => 'শিবগঞ্জ', 'url' => 'shibganj.chapainawabganj.gov.bd'),
            array('district_slug' => 'naogaon', 'name' => 'Mohadevpur', 'name_bn' => 'মহাদেবপুর', 'url' => 'mohadevpur.naogaon.gov.bd'),
            array('district_slug' => 'naogaon', 'name' => 'Badalgachi', 'name_bn' => 'বদলগাছী', 'url' => 'badalgachi.naogaon.gov.bd'),
            array('district_slug' => 'naogaon', 'name' => 'Patnitala', 'name_bn' => 'পত্নিতলা', 'url' => 'patnitala.naogaon.gov.bd'),
            array('district_slug' => 'naogaon', 'name' => 'Dhamoirhat', 'name_bn' => 'ধামইরহাট', 'url' => 'dhamoirhat.naogaon.gov.bd'),
            array('district_slug' => 'naogaon', 'name' => 'Niamatpur', 'name_bn' => 'নিয়ামতপুর', 'url' => 'niamatpur.naogaon.gov.bd'),
            array('district_slug' => 'naogaon', 'name' => 'Manda', 'name_bn' => 'মান্দা', 'url' => 'manda.naogaon.gov.bd'),
            array('district_slug' => 'naogaon', 'name' => 'Atrai', 'name_bn' => 'আত্রাই', 'url' => 'atrai.naogaon.gov.bd'),
            array('district_slug' => 'naogaon', 'name' => 'Raninagar', 'name_bn' => 'রাণীনগর', 'url' => 'raninagar.naogaon.gov.bd'),
            array('district_slug' => 'naogaon', 'name' => 'Naogaon Sadar', 'name_bn' => 'নওগাঁ সদর', 'url' => 'naogaonsadar.naogaon.gov.bd'),
            array('district_slug' => 'naogaon', 'name' => 'Porsha', 'name_bn' => 'পোরশা', 'url' => 'porsha.naogaon.gov.bd'),
            array('district_slug' => 'naogaon', 'name' => 'Sapahar', 'name_bn' => 'সাপাহার', 'url' => 'sapahar.naogaon.gov.bd'),
            array('district_slug' => 'jashore', 'name' => 'Manirampur', 'name_bn' => 'মণিরামপুর', 'url' => 'manirampur.jessore.gov.bd'),
            array('district_slug' => 'jashore', 'name' => 'Abhaynagar', 'name_bn' => 'অভয়নগর', 'url' => 'abhaynagar.jessore.gov.bd'),
            array('district_slug' => 'jashore', 'name' => 'Bagherpara', 'name_bn' => 'বাঘারপাড়া', 'url' => 'bagherpara.jessore.gov.bd'),
            array('district_slug' => 'jashore', 'name' => 'Chougachha', 'name_bn' => 'চৌগাছা', 'url' => 'chougachha.jessore.gov.bd'),
            array('district_slug' => 'jashore', 'name' => 'Jhikargacha', 'name_bn' => 'ঝিকরগাছা', 'url' => 'jhikargacha.jessore.gov.bd'),
            array('district_slug' => 'jashore', 'name' => 'Keshabpur', 'name_bn' => 'কেশবপুর', 'url' => 'keshabpur.jessore.gov.bd'),
            array('district_slug' => 'jashore', 'name' => 'Jessore Sadar', 'name_bn' => 'যশোর সদর', 'url' => 'sadar.jessore.gov.bd'),
            array('district_slug' => 'jashore', 'name' => 'Sharsha', 'name_bn' => 'শার্শা', 'url' => 'sharsha.jessore.gov.bd'),
            array('district_slug' => 'satkhira', 'name' => 'Assasuni', 'name_bn' => 'আশাশুনি', 'url' => 'assasuni.satkhira.gov.bd'),
            array('district_slug' => 'satkhira', 'name' => 'Debhata', 'name_bn' => 'দেবহাটা', 'url' => 'debhata.satkhira.gov.bd'),
            array('district_slug' => 'satkhira', 'name' => 'Kalaroa', 'name_bn' => 'কলারোয়া', 'url' => 'kalaroa.satkhira.gov.bd'),
            array('district_slug' => 'satkhira', 'name' => 'Satkhira Sadar', 'name_bn' => 'সাতক্ষীরা সদর', 'url' => 'satkhirasadar.satkhira.gov.bd'),
            array('district_slug' => 'satkhira', 'name' => 'Shyamnagar', 'name_bn' => 'শ্যামনগর', 'url' => 'shyamnagar.satkhira.gov.bd'),
            array('district_slug' => 'satkhira', 'name' => 'Tala', 'name_bn' => 'তালা', 'url' => 'tala.satkhira.gov.bd'),
            array('district_slug' => 'satkhira', 'name' => 'Kaliganj', 'name_bn' => 'কালিগঞ্জ', 'url' => 'kaliganj.satkhira.gov.bd'),
            array('district_slug' => 'meherpur', 'name' => 'Mujibnagar', 'name_bn' => 'মুজিবনগর', 'url' => 'mujibnagar.meherpur.gov.bd'),
            array('district_slug' => 'meherpur', 'name' => 'Meherpur Sadar', 'name_bn' => 'মেহেরপুর সদর', 'url' => 'meherpursadar.meherpur.gov.bd'),
            array('district_slug' => 'meherpur', 'name' => 'Gangni', 'name_bn' => 'গাংনী', 'url' => 'gangni.meherpur.gov.bd'),
            array('district_slug' => 'narail', 'name' => 'Narail Sadar', 'name_bn' => 'নড়াইল সদর', 'url' => 'narailsadar.narail.gov.bd'),
            array('district_slug' => 'narail', 'name' => 'Lohagara', 'name_bn' => 'লোহাগড়া', 'url' => 'lohagara.narail.gov.bd'),
            array('district_slug' => 'narail', 'name' => 'Kalia', 'name_bn' => 'কালিয়া', 'url' => 'kalia.narail.gov.bd'),
            array('district_slug' => 'chuadanga', 'name' => 'Chuadanga Sadar', 'name_bn' => 'চুয়াডাঙ্গা সদর', 'url' => 'chuadangasadar.chuadanga.gov.bd'),
            array('district_slug' => 'chuadanga', 'name' => 'Alamdanga', 'name_bn' => 'আলমডাঙ্গা', 'url' => 'alamdanga.chuadanga.gov.bd'),
            array('district_slug' => 'chuadanga', 'name' => 'Damurhuda', 'name_bn' => 'দামুড়হুদা', 'url' => 'damurhuda.chuadanga.gov.bd'),
            array('district_slug' => 'chuadanga', 'name' => 'Jibannagar', 'name_bn' => 'জীবননগর', 'url' => 'jibannagar.chuadanga.gov.bd'),
            array('district_slug' => 'kushtia', 'name' => 'Kushtia Sadar', 'name_bn' => 'কুষ্টিয়া সদর', 'url' => 'kushtiasadar.kushtia.gov.bd'),
            array('district_slug' => 'kushtia', 'name' => 'Kumarkhali', 'name_bn' => 'কুমারখালী', 'url' => 'kumarkhali.kushtia.gov.bd'),
            array('district_slug' => 'kushtia', 'name' => 'Khoksa', 'name_bn' => 'খোকসা', 'url' => 'khoksa.kushtia.gov.bd'),
            array('district_slug' => 'kushtia', 'name' => 'Mirpur', 'name_bn' => 'মিরপুর', 'url' => 'mirpurkushtia.kushtia.gov.bd'),
            array('district_slug' => 'kushtia', 'name' => 'Daulatpur', 'name_bn' => 'দৌলতপুর', 'url' => 'daulatpur.kushtia.gov.bd'),
            array('district_slug' => 'kushtia', 'name' => 'Bheramara', 'name_bn' => 'ভেড়ামারা', 'url' => 'bheramara.kushtia.gov.bd'),
            array('district_slug' => 'magura', 'name' => 'Shalikha', 'name_bn' => 'শালিখা', 'url' => 'shalikha.magura.gov.bd'),
            array('district_slug' => 'magura', 'name' => 'Sreepur', 'name_bn' => 'শ্রীপুর', 'url' => 'sreepur.magura.gov.bd'),
            array('district_slug' => 'magura', 'name' => 'Magura Sadar', 'name_bn' => 'মাগুরা সদর', 'url' => 'magurasadar.magura.gov.bd'),
            array('district_slug' => 'magura', 'name' => 'Mohammadpur', 'name_bn' => 'মহম্মদপুর', 'url' => 'mohammadpur.magura.gov.bd'),
            array('district_slug' => 'khulna', 'name' => 'Paikgasa', 'name_bn' => 'পাইকগাছা', 'url' => 'paikgasa.khulna.gov.bd'),
            array('district_slug' => 'khulna', 'name' => 'Fultola', 'name_bn' => 'ফুলতলা', 'url' => 'fultola.khulna.gov.bd'),
            array('district_slug' => 'khulna', 'name' => 'Digholia', 'name_bn' => 'দিঘলিয়া', 'url' => 'digholia.khulna.gov.bd'),
            array('district_slug' => 'khulna', 'name' => 'Rupsha', 'name_bn' => 'রূপসা', 'url' => 'rupsha.khulna.gov.bd'),
            array('district_slug' => 'khulna', 'name' => 'Terokhada', 'name_bn' => 'তেরখাদা', 'url' => 'terokhada.khulna.gov.bd'),
            array('district_slug' => 'khulna', 'name' => 'Dumuria', 'name_bn' => 'ডুমুরিয়া', 'url' => 'dumuria.khulna.gov.bd'),
            array('district_slug' => 'khulna', 'name' => 'Botiaghata', 'name_bn' => 'বটিয়াঘাটা', 'url' => 'botiaghata.khulna.gov.bd'),
            array('district_slug' => 'khulna', 'name' => 'Dakop', 'name_bn' => 'দাকোপ', 'url' => 'dakop.khulna.gov.bd'),
            array('district_slug' => 'khulna', 'name' => 'Koyra', 'name_bn' => 'কয়রা', 'url' => 'koyra.khulna.gov.bd'),
            array('district_slug' => 'bagerhat', 'name' => 'Fakirhat', 'name_bn' => 'ফকিরহাট', 'url' => 'fakirhat.bagerhat.gov.bd'),
            array('district_slug' => 'bagerhat', 'name' => 'Bagerhat Sadar', 'name_bn' => 'বাগেরহাট সদর', 'url' => 'sadar.bagerhat.gov.bd'),
            array('district_slug' => 'bagerhat', 'name' => 'Mollahat', 'name_bn' => 'মোল্লাহাট', 'url' => 'mollahat.bagerhat.gov.bd'),
            array('district_slug' => 'bagerhat', 'name' => 'Sarankhola', 'name_bn' => 'শরণখোলা', 'url' => 'sarankhola.bagerhat.gov.bd'),
            array('district_slug' => 'bagerhat', 'name' => 'Rampal', 'name_bn' => 'রামপাল', 'url' => 'rampal.bagerhat.gov.bd'),
            array('district_slug' => 'bagerhat', 'name' => 'Morrelganj', 'name_bn' => 'মোড়েলগঞ্জ', 'url' => 'morrelganj.bagerhat.gov.bd'),
            array('district_slug' => 'bagerhat', 'name' => 'Kachua', 'name_bn' => 'কচুয়া', 'url' => 'kachua.bagerhat.gov.bd'),
            array('district_slug' => 'bagerhat', 'name' => 'Mongla', 'name_bn' => 'মোংলা', 'url' => 'mongla.bagerhat.gov.bd'),
            array('district_slug' => 'bagerhat', 'name' => 'Chitalmari', 'name_bn' => 'চিতলমারী', 'url' => 'chitalmari.bagerhat.gov.bd'),
            array('district_slug' => 'jhenaidah', 'name' => 'Jhenaidah Sadar', 'name_bn' => 'ঝিনাইদহ সদর', 'url' => 'sadar.jhenaidah.gov.bd'),
            array('district_slug' => 'jhenaidah', 'name' => 'Shailkupa', 'name_bn' => 'শৈলকুপা', 'url' => 'shailkupa.jhenaidah.gov.bd'),
            array('district_slug' => 'jhenaidah', 'name' => 'Harinakundu', 'name_bn' => 'হরিণাকুন্ডু', 'url' => 'harinakundu.jhenaidah.gov.bd'),
            array('district_slug' => 'jhenaidah', 'name' => 'Kaliganj', 'name_bn' => 'কালীগঞ্জ', 'url' => 'kaliganj.jhenaidah.gov.bd'),
            array('district_slug' => 'jhenaidah', 'name' => 'Kotchandpur', 'name_bn' => 'কোটচাঁদপুর', 'url' => 'kotchandpur.jhenaidah.gov.bd'),
            array('district_slug' => 'jhenaidah', 'name' => 'Moheshpur', 'name_bn' => 'মহেশপুর', 'url' => 'moheshpur.jhenaidah.gov.bd'),
            array('district_slug' => 'jhalakathi', 'name' => 'Jhalakathi Sadar', 'name_bn' => 'ঝালকাঠি সদর', 'url' => 'sadar.jhalakathi.gov.bd'),
            array('district_slug' => 'jhalakathi', 'name' => 'Kathalia', 'name_bn' => 'কাঠালিয়া', 'url' => 'kathalia.jhalakathi.gov.bd'),
            array('district_slug' => 'jhalakathi', 'name' => 'Nalchity', 'name_bn' => 'নলছিটি', 'url' => 'nalchity.jhalakathi.gov.bd'),
            array('district_slug' => 'jhalakathi', 'name' => 'Rajapur', 'name_bn' => 'রাজাপুর', 'url' => 'rajapur.jhalakathi.gov.bd'),
            array('district_slug' => 'patuakhali', 'name' => 'Bauphal', 'name_bn' => 'বাউফল', 'url' => 'bauphal.patuakhali.gov.bd'),
            array('district_slug' => 'patuakhali', 'name' => 'Patuakhali Sadar', 'name_bn' => 'পটুয়াখালী সদর', 'url' => 'sadar.patuakhali.gov.bd'),
            array('district_slug' => 'patuakhali', 'name' => 'Dumki', 'name_bn' => 'দুমকি', 'url' => 'dumki.patuakhali.gov.bd'),
            array('district_slug' => 'patuakhali', 'name' => 'Dashmina', 'name_bn' => 'দশমিনা', 'url' => 'dashmina.patuakhali.gov.bd'),
            array('district_slug' => 'patuakhali', 'name' => 'Kalapara', 'name_bn' => 'কলাপাড়া', 'url' => 'kalapara.patuakhali.gov.bd'),
            array('district_slug' => 'patuakhali', 'name' => 'Mirzaganj', 'name_bn' => 'মির্জাগঞ্জ', 'url' => 'mirzaganj.patuakhali.gov.bd'),
            array('district_slug' => 'patuakhali', 'name' => 'Galachipa', 'name_bn' => 'গলাচিপা', 'url' => 'galachipa.patuakhali.gov.bd'),
            array('district_slug' => 'patuakhali', 'name' => 'Rangabali', 'name_bn' => 'রাঙ্গাবালী', 'url' => 'rangabali.patuakhali.gov.bd'),
            array('district_slug' => 'pirojpur', 'name' => 'Pirojpur Sadar', 'name_bn' => 'পিরোজপুর সদর', 'url' => 'sadar.pirojpur.gov.bd'),
            array('district_slug' => 'pirojpur', 'name' => 'Nazirpur', 'name_bn' => 'নাজিরপুর', 'url' => 'nazirpur.pirojpur.gov.bd'),
            array('district_slug' => 'pirojpur', 'name' => 'Kawkhali', 'name_bn' => 'কাউখালী', 'url' => 'kawkhali.pirojpur.gov.bd'),
            array('district_slug' => 'pirojpur', 'name' => 'Zianagar', 'name_bn' => 'জিয়ানগর', 'url' => 'zianagar.pirojpur.gov.bd'),
            array('district_slug' => 'pirojpur', 'name' => 'Bhandaria', 'name_bn' => 'ভান্ডারিয়া', 'url' => 'bhandaria.pirojpur.gov.bd'),
            array('district_slug' => 'pirojpur', 'name' => 'Mathbaria', 'name_bn' => 'মঠবাড়ীয়া', 'url' => 'mathbaria.pirojpur.gov.bd'),
            array('district_slug' => 'pirojpur', 'name' => 'Nesarabad', 'name_bn' => 'নেছারাবাদ', 'url' => 'nesarabad.pirojpur.gov.bd'),
            array('district_slug' => 'barisal', 'name' => 'Barisal Sadar', 'name_bn' => 'বরিশাল সদর', 'url' => 'barisalsadar.barisal.gov.bd'),
            array('district_slug' => 'barisal', 'name' => 'Bakerganj', 'name_bn' => 'বাকেরগঞ্জ', 'url' => 'bakerganj.barisal.gov.bd'),
            array('district_slug' => 'barisal', 'name' => 'Babuganj', 'name_bn' => 'বাবুগঞ্জ', 'url' => 'babuganj.barisal.gov.bd'),
            array('district_slug' => 'barisal', 'name' => 'Wazirpur', 'name_bn' => 'উজিরপুর', 'url' => 'wazirpur.barisal.gov.bd'),
            array('district_slug' => 'barisal', 'name' => 'Banaripara', 'name_bn' => 'বানারীপাড়া', 'url' => 'banaripara.barisal.gov.bd'),
            array('district_slug' => 'barisal', 'name' => 'Gournadi', 'name_bn' => 'গৌরনদী', 'url' => 'gournadi.barisal.gov.bd'),
            array('district_slug' => 'barisal', 'name' => 'Agailjhara', 'name_bn' => 'আগৈলঝাড়া', 'url' => 'agailjhara.barisal.gov.bd'),
            array('district_slug' => 'barisal', 'name' => 'Mehendiganj', 'name_bn' => 'মেহেন্দিগঞ্জ', 'url' => 'mehendiganj.barisal.gov.bd'),
            array('district_slug' => 'barisal', 'name' => 'Muladi', 'name_bn' => 'মুলাদী', 'url' => 'muladi.barisal.gov.bd'),
            array('district_slug' => 'barisal', 'name' => 'Hizla', 'name_bn' => 'হিজলা', 'url' => 'hizla.barisal.gov.bd'),
            array('district_slug' => 'bhola', 'name' => 'Bhola Sadar', 'name_bn' => 'ভোলা সদর', 'url' => 'sadar.bhola.gov.bd'),
            array('district_slug' => 'bhola', 'name' => 'Borhan Sddin', 'name_bn' => 'বোরহান উদ্দিন', 'url' => 'borhanuddin.bhola.gov.bd'),
            array('district_slug' => 'bhola', 'name' => 'Charfesson', 'name_bn' => 'চরফ্যাশন', 'url' => 'charfesson.bhola.gov.bd'),
            array('district_slug' => 'bhola', 'name' => 'Doulatkhan', 'name_bn' => 'দৌলতখান', 'url' => 'doulatkhan.bhola.gov.bd'),
            array('district_slug' => 'bhola', 'name' => 'Monpura', 'name_bn' => 'মনপুরা', 'url' => 'monpura.bhola.gov.bd'),
            array('district_slug' => 'bhola', 'name' => 'Tazumuddin', 'name_bn' => 'তজুমদ্দিন', 'url' => 'tazumuddin.bhola.gov.bd'),
            array('district_slug' => 'bhola', 'name' => 'Lalmohan', 'name_bn' => 'লালমোহন', 'url' => 'lalmohan.bhola.gov.bd'),
            array('district_slug' => 'barguna', 'name' => 'Amtali', 'name_bn' => 'আমতলী', 'url' => 'amtali.barguna.gov.bd'),
            array('district_slug' => 'barguna', 'name' => 'Barguna Sadar', 'name_bn' => 'বরগুনা সদর', 'url' => 'sadar.barguna.gov.bd'),
            array('district_slug' => 'barguna', 'name' => 'Betagi', 'name_bn' => 'বেতাগী', 'url' => 'betagi.barguna.gov.bd'),
            array('district_slug' => 'barguna', 'name' => 'Bamna', 'name_bn' => 'বামনা', 'url' => 'bamna.barguna.gov.bd'),
            array('district_slug' => 'barguna', 'name' => 'Pathorghata', 'name_bn' => 'পাথরঘাটা', 'url' => 'pathorghata.barguna.gov.bd'),
            array('district_slug' => 'barguna', 'name' => 'Taltali', 'name_bn' => 'তালতলি', 'url' => 'taltali.barguna.gov.bd'),
            array('district_slug' => 'sylhet', 'name' => 'Balaganj', 'name_bn' => 'বালাগঞ্জ', 'url' => 'balaganj.sylhet.gov.bd'),
            array('district_slug' => 'sylhet', 'name' => 'Beanibazar', 'name_bn' => 'বিয়ানীবাজার', 'url' => 'beanibazar.sylhet.gov.bd'),
            array('district_slug' => 'sylhet', 'name' => 'Bishwanath', 'name_bn' => 'বিশ্বনাথ', 'url' => 'bishwanath.sylhet.gov.bd'),
            array('district_slug' => 'sylhet', 'name' => 'Companiganj', 'name_bn' => 'কোম্পানীগঞ্জ', 'url' => 'companiganj.sylhet.gov.bd'),
            array('district_slug' => 'sylhet', 'name' => 'Fenchuganj', 'name_bn' => 'ফেঞ্চুগঞ্জ', 'url' => 'fenchuganj.sylhet.gov.bd'),
            array('district_slug' => 'sylhet', 'name' => 'Golapganj', 'name_bn' => 'গোলাপগঞ্জ', 'url' => 'golapganj.sylhet.gov.bd'),
            array('district_slug' => 'sylhet', 'name' => 'Gowainghat', 'name_bn' => 'গোয়াইনঘাট', 'url' => 'gowainghat.sylhet.gov.bd'),
            array('district_slug' => 'sylhet', 'name' => 'Jaintiapur', 'name_bn' => 'জৈন্তাপুর', 'url' => 'jaintiapur.sylhet.gov.bd'),
            array('district_slug' => 'sylhet', 'name' => 'Kanaighat', 'name_bn' => 'কানাইঘাট', 'url' => 'kanaighat.sylhet.gov.bd'),
            array('district_slug' => 'sylhet', 'name' => 'Sylhet Sadar', 'name_bn' => 'সিলেট সদর', 'url' => 'sylhetsadar.sylhet.gov.bd'),
            array('district_slug' => 'sylhet', 'name' => 'Zakiganj', 'name_bn' => 'জকিগঞ্জ', 'url' => 'zakiganj.sylhet.gov.bd'),
            array('district_slug' => 'sylhet', 'name' => 'Dakshinsurma', 'name_bn' => 'দক্ষিণ সুরমা', 'url' => 'dakshinsurma.sylhet.gov.bd'),
            array('district_slug' => 'sylhet', 'name' => 'Osmaninagar', 'name_bn' => 'ওসমানী নগর', 'url' => 'osmaninagar.sylhet.gov.bd'),
            array('district_slug' => 'moulvibazar', 'name' => 'Barlekha', 'name_bn' => 'বড়লেখা', 'url' => 'barlekha.moulvibazar.gov.bd'),
            array('district_slug' => 'moulvibazar', 'name' => 'Kamolganj', 'name_bn' => 'কমলগঞ্জ', 'url' => 'kamolganj.moulvibazar.gov.bd'),
            array('district_slug' => 'moulvibazar', 'name' => 'Kulaura', 'name_bn' => 'কুলাউড়া', 'url' => 'kulaura.moulvibazar.gov.bd'),
            array('district_slug' => 'moulvibazar', 'name' => 'Moulvibazar Sadar', 'name_bn' => 'মৌলভীবাজার সদর', 'url' => 'moulvibazarsadar.moulvibazar.gov.bd'),
            array('district_slug' => 'moulvibazar', 'name' => 'Rajnagar', 'name_bn' => 'রাজনগর', 'url' => 'rajnagar.moulvibazar.gov.bd'),
            array('district_slug' => 'moulvibazar', 'name' => 'Sreemangal', 'name_bn' => 'শ্রীমঙ্গল', 'url' => 'sreemangal.moulvibazar.gov.bd'),
            array('district_slug' => 'moulvibazar', 'name' => 'Juri', 'name_bn' => 'জুড়ী', 'url' => 'juri.moulvibazar.gov.bd'),
            array('district_slug' => 'habiganj', 'name' => 'Nabiganj', 'name_bn' => 'নবীগঞ্জ', 'url' => 'nabiganj.habiganj.gov.bd'),
            array('district_slug' => 'habiganj', 'name' => 'Bahubal', 'name_bn' => 'বাহুবল', 'url' => 'bahubal.habiganj.gov.bd'),
            array('district_slug' => 'habiganj', 'name' => 'Ajmiriganj', 'name_bn' => 'আজমিরীগঞ্জ', 'url' => 'ajmiriganj.habiganj.gov.bd'),
            array('district_slug' => 'habiganj', 'name' => 'Baniachong', 'name_bn' => 'বানিয়াচং', 'url' => 'baniachong.habiganj.gov.bd'),
            array('district_slug' => 'habiganj', 'name' => 'Lakhai', 'name_bn' => 'লাখাই', 'url' => 'lakhai.habiganj.gov.bd'),
            array('district_slug' => 'habiganj', 'name' => 'Chunarughat', 'name_bn' => 'চুনারুঘাট', 'url' => 'chunarughat.habiganj.gov.bd'),
            array('district_slug' => 'habiganj', 'name' => 'Habiganj Sadar', 'name_bn' => 'হবিগঞ্জ সদর', 'url' => 'habiganjsadar.habiganj.gov.bd'),
            array('district_slug' => 'habiganj', 'name' => 'Madhabpur', 'name_bn' => 'মাধবপুর', 'url' => 'madhabpur.habiganj.gov.bd'),
            array('district_slug' => 'sunamganj', 'name' => 'Sunamganj Sadar', 'name_bn' => 'সুনামগঞ্জ সদর', 'url' => 'sadar.sunamganj.gov.bd'),
            array('district_slug' => 'sunamganj', 'name' => 'South Sunamganj', 'name_bn' => 'দক্ষিণ সুনামগঞ্জ', 'url' => 'southsunamganj.sunamganj.gov.bd'),
            array('district_slug' => 'sunamganj', 'name' => 'Bishwambarpur', 'name_bn' => 'বিশ্বম্ভরপুর', 'url' => 'bishwambarpur.sunamganj.gov.bd'),
            array('district_slug' => 'sunamganj', 'name' => 'Chhatak', 'name_bn' => 'ছাতক', 'url' => 'chhatak.sunamganj.gov.bd'),
            array('district_slug' => 'sunamganj', 'name' => 'Jagannathpur', 'name_bn' => 'জগন্নাথপুর', 'url' => 'jagannathpur.sunamganj.gov.bd'),
            array('district_slug' => 'sunamganj', 'name' => 'Dowarabazar', 'name_bn' => 'দোয়ারাবাজার', 'url' => 'dowarabazar.sunamganj.gov.bd'),
            array('district_slug' => 'sunamganj', 'name' => 'Tahirpur', 'name_bn' => 'তাহিরপুর', 'url' => 'tahirpur.sunamganj.gov.bd'),
            array('district_slug' => 'sunamganj', 'name' => 'Dharmapasha', 'name_bn' => 'ধর্মপাশা', 'url' => 'dharmapasha.sunamganj.gov.bd'),
            array('district_slug' => 'sunamganj', 'name' => 'Jamalganj', 'name_bn' => 'জামালগঞ্জ', 'url' => 'jamalganj.sunamganj.gov.bd'),
            array('district_slug' => 'sunamganj', 'name' => 'Shalla', 'name_bn' => 'শাল্লা', 'url' => 'shalla.sunamganj.gov.bd'),
            array('district_slug' => 'sunamganj', 'name' => 'Derai', 'name_bn' => 'দিরাই', 'url' => 'derai.sunamganj.gov.bd'),
            array('district_slug' => 'narsingdi', 'name' => 'Belabo', 'name_bn' => 'বেলাবো', 'url' => 'belabo.narsingdi.gov.bd'),
            array('district_slug' => 'narsingdi', 'name' => 'Monohardi', 'name_bn' => 'মনোহরদী', 'url' => 'monohardi.narsingdi.gov.bd'),
            array('district_slug' => 'narsingdi', 'name' => 'Narsingdi Sadar', 'name_bn' => 'নরসিংদী সদর', 'url' => 'narsingdisadar.narsingdi.gov.bd'),
            array('district_slug' => 'narsingdi', 'name' => 'Palash', 'name_bn' => 'পলাশ', 'url' => 'palash.narsingdi.gov.bd'),
            array('district_slug' => 'narsingdi', 'name' => 'Raipura', 'name_bn' => 'রায়পুরা', 'url' => 'raipura.narsingdi.gov.bd'),
            array('district_slug' => 'narsingdi', 'name' => 'Shibpur', 'name_bn' => 'শিবপুর', 'url' => 'shibpur.narsingdi.gov.bd'),
            array('district_slug' => 'gazipur', 'name' => 'Kaliganj', 'name_bn' => 'কালীগঞ্জ', 'url' => 'kaliganj.gazipur.gov.bd'),
            array('district_slug' => 'gazipur', 'name' => 'Kaliakair', 'name_bn' => 'কালিয়াকৈর', 'url' => 'kaliakair.gazipur.gov.bd'),
            array('district_slug' => 'gazipur', 'name' => 'Kapasia', 'name_bn' => 'কাপাসিয়া', 'url' => 'kapasia.gazipur.gov.bd'),
            array('district_slug' => 'gazipur', 'name' => 'Gazipur Sadar', 'name_bn' => 'গাজীপুর সদর', 'url' => 'sadar.gazipur.gov.bd'),
            array('district_slug' => 'gazipur', 'name' => 'Sreepur', 'name_bn' => 'শ্রীপুর', 'url' => 'sreepur.gazipur.gov.bd'),
            array('district_slug' => 'shariatpur', 'name' => 'Shariatpur Sadar', 'name_bn' => 'শরিয়তপুর সদর', 'url' => 'sadar.shariatpur.gov.bd'),
            array('district_slug' => 'shariatpur', 'name' => 'Naria', 'name_bn' => 'নড়িয়া', 'url' => 'naria.shariatpur.gov.bd'),
            array('district_slug' => 'shariatpur', 'name' => 'Zajira', 'name_bn' => 'জাজিরা', 'url' => 'zajira.shariatpur.gov.bd'),
            array('district_slug' => 'shariatpur', 'name' => 'Gosairhat', 'name_bn' => 'গোসাইরহাট', 'url' => 'gosairhat.shariatpur.gov.bd'),
            array('district_slug' => 'shariatpur', 'name' => 'Bhedarganj', 'name_bn' => 'ভেদরগঞ্জ', 'url' => 'bhedarganj.shariatpur.gov.bd'),
            array('district_slug' => 'shariatpur', 'name' => 'Damudya', 'name_bn' => 'ডামুড্যা', 'url' => 'damudya.shariatpur.gov.bd'),
            array('district_slug' => 'narayanganj', 'name' => 'Araihazar', 'name_bn' => 'আড়াইহাজার', 'url' => 'araihazar.narayanganj.gov.bd'),
            array('district_slug' => 'narayanganj', 'name' => 'Bandar', 'name_bn' => 'বন্দর', 'url' => 'bandar.narayanganj.gov.bd'),
            array('district_slug' => 'narayanganj', 'name' => 'Narayanganj Sadar', 'name_bn' => 'নারায়নগঞ্জ সদর', 'url' => 'narayanganjsadar.narayanganj.gov.bd'),
            array('district_slug' => 'narayanganj', 'name' => 'Rupganj', 'name_bn' => 'রূপগঞ্জ', 'url' => 'rupganj.narayanganj.gov.bd'),
            array('district_slug' => 'narayanganj', 'name' => 'Sonargaon', 'name_bn' => 'সোনারগাঁ', 'url' => 'sonargaon.narayanganj.gov.bd'),
            array('district_slug' => 'tangail', 'name' => 'Basail', 'name_bn' => 'বাসাইল', 'url' => 'basail.tangail.gov.bd'),
            array('district_slug' => 'tangail', 'name' => 'Bhuapur', 'name_bn' => 'ভুয়াপুর', 'url' => 'bhuapur.tangail.gov.bd'),
            array('district_slug' => 'tangail', 'name' => 'Delduar', 'name_bn' => 'দেলদুয়ার', 'url' => 'delduar.tangail.gov.bd'),
            array('district_slug' => 'tangail', 'name' => 'Ghatail', 'name_bn' => 'ঘাটাইল', 'url' => 'ghatail.tangail.gov.bd'),
            array('district_slug' => 'tangail', 'name' => 'Gopalpur', 'name_bn' => 'গোপালপুর', 'url' => 'gopalpur.tangail.gov.bd'),
            array('district_slug' => 'tangail', 'name' => 'Madhupur', 'name_bn' => 'মধুপুর', 'url' => 'madhupur.tangail.gov.bd'),
            array('district_slug' => 'tangail', 'name' => 'Mirzapur', 'name_bn' => 'মির্জাপুর', 'url' => 'mirzapur.tangail.gov.bd'),
            array('district_slug' => 'tangail', 'name' => 'Nagarpur', 'name_bn' => 'নাগরপুর', 'url' => 'nagarpur.tangail.gov.bd'),
            array('district_slug' => 'tangail', 'name' => 'Sakhipur', 'name_bn' => 'সখিপুর', 'url' => 'sakhipur.tangail.gov.bd'),
            array('district_slug' => 'tangail', 'name' => 'Tangail Sadar', 'name_bn' => 'টাঙ্গাইল সদর', 'url' => 'tangailsadar.tangail.gov.bd'),
            array('district_slug' => 'tangail', 'name' => 'Kalihati', 'name_bn' => 'কালিহাতী', 'url' => 'kalihati.tangail.gov.bd'),
            array('district_slug' => 'tangail', 'name' => 'Dhanbari', 'name_bn' => 'ধনবাড়ী', 'url' => 'dhanbari.tangail.gov.bd'),
            array('district_slug' => 'kishoreganj', 'name' => 'Itna', 'name_bn' => 'ইটনা', 'url' => 'itna.kishoreganj.gov.bd'),
            array('district_slug' => 'kishoreganj', 'name' => 'Katiadi', 'name_bn' => 'কটিয়াদী', 'url' => 'katiadi.kishoreganj.gov.bd'),
            array('district_slug' => 'kishoreganj', 'name' => 'Bhairab', 'name_bn' => 'ভৈরব', 'url' => 'bhairab.kishoreganj.gov.bd'),
            array('district_slug' => 'kishoreganj', 'name' => 'Tarail', 'name_bn' => 'তাড়াইল', 'url' => 'tarail.kishoreganj.gov.bd'),
            array('district_slug' => 'kishoreganj', 'name' => 'Hossainpur', 'name_bn' => 'হোসেনপুর', 'url' => 'hossainpur.kishoreganj.gov.bd'),
            array('district_slug' => 'kishoreganj', 'name' => 'Pakundia', 'name_bn' => 'পাকুন্দিয়া', 'url' => 'pakundia.kishoreganj.gov.bd'),
            array('district_slug' => 'kishoreganj', 'name' => 'Kuliarchar', 'name_bn' => 'কুলিয়ারচর', 'url' => 'kuliarchar.kishoreganj.gov.bd'),
            array('district_slug' => 'kishoreganj', 'name' => 'Kishoreganj Sadar', 'name_bn' => 'কিশোরগঞ্জ সদর', 'url' => 'kishoreganjsadar.kishoreganj.gov.bd'),
            array('district_slug' => 'kishoreganj', 'name' => 'Karimgonj', 'name_bn' => 'করিমগঞ্জ', 'url' => 'karimgonj.kishoreganj.gov.bd'),
            array('district_slug' => 'kishoreganj', 'name' => 'Bajitpur', 'name_bn' => 'বাজিতপুর', 'url' => 'bajitpur.kishoreganj.gov.bd'),
            array('district_slug' => 'kishoreganj', 'name' => 'Austagram', 'name_bn' => 'অষ্টগ্রাম', 'url' => 'austagram.kishoreganj.gov.bd'),
            array('district_slug' => 'kishoreganj', 'name' => 'Mithamoin', 'name_bn' => 'মিঠামইন', 'url' => 'mithamoin.kishoreganj.gov.bd'),
            array('district_slug' => 'kishoreganj', 'name' => 'Nikli', 'name_bn' => 'নিকলী', 'url' => 'nikli.kishoreganj.gov.bd'),
            array('district_slug' => 'manikganj', 'name' => 'Harirampur', 'name_bn' => 'হরিরামপুর', 'url' => 'harirampur.manikganj.gov.bd'),
            array('district_slug' => 'manikganj', 'name' => 'Saturia', 'name_bn' => 'সাটুরিয়া', 'url' => 'saturia.manikganj.gov.bd'),
            array('district_slug' => 'manikganj', 'name' => 'Manikganj Sadar', 'name_bn' => 'মানিকগঞ্জ সদর', 'url' => 'sadar.manikganj.gov.bd'),
            array('district_slug' => 'manikganj', 'name' => 'Gior', 'name_bn' => 'ঘিওর', 'url' => 'gior.manikganj.gov.bd'),
            array('district_slug' => 'manikganj', 'name' => 'Shibaloy', 'name_bn' => 'শিবালয়', 'url' => 'shibaloy.manikganj.gov.bd'),
            array('district_slug' => 'manikganj', 'name' => 'Doulatpur', 'name_bn' => 'দৌলতপুর', 'url' => 'doulatpur.manikganj.gov.bd'),
            array('district_slug' => 'manikganj', 'name' => 'Singiar', 'name_bn' => 'সিংগাইর', 'url' => 'singiar.manikganj.gov.bd'),
            array('district_slug' => 'dhaka', 'name' => 'Savar', 'name_bn' => 'সাভার', 'url' => 'savar.dhaka.gov.bd'),
            array('district_slug' => 'dhaka', 'name' => 'Dhamrai', 'name_bn' => 'ধামরাই', 'url' => 'dhamrai.dhaka.gov.bd'),
            array('district_slug' => 'dhaka', 'name' => 'Keraniganj', 'name_bn' => 'কেরাণীগঞ্জ', 'url' => 'keraniganj.dhaka.gov.bd'),
            array('district_slug' => 'dhaka', 'name' => 'Nawabganj', 'name_bn' => 'নবাবগঞ্জ', 'url' => 'nawabganj.dhaka.gov.bd'),
            array('district_slug' => 'dhaka', 'name' => 'Dohar', 'name_bn' => 'দোহার', 'url' => 'dohar.dhaka.gov.bd'),
            array('district_slug' => 'munshiganj', 'name' => 'Munshiganj Sadar', 'name_bn' => 'মুন্সিগঞ্জ সদর', 'url' => 'sadar.munshiganj.gov.bd'),
            array('district_slug' => 'munshiganj', 'name' => 'Sreenagar', 'name_bn' => 'শ্রীনগর', 'url' => 'sreenagar.munshiganj.gov.bd'),
            array('district_slug' => 'munshiganj', 'name' => 'Sirajdikhan', 'name_bn' => 'সিরাজদিখান', 'url' => 'sirajdikhan.munshiganj.gov.bd'),
            array('district_slug' => 'munshiganj', 'name' => 'Louhajanj', 'name_bn' => 'লৌহজং', 'url' => 'louhajanj.munshiganj.gov.bd'),
            array('district_slug' => 'munshiganj', 'name' => 'Gajaria', 'name_bn' => 'গজারিয়া', 'url' => 'gajaria.munshiganj.gov.bd'),
            array('district_slug' => 'munshiganj', 'name' => 'Tongibari', 'name_bn' => 'টংগীবাড়ি', 'url' => 'tongibari.munshiganj.gov.bd'),
            array('district_slug' => 'rajbari', 'name' => 'Rajbari Sadar', 'name_bn' => 'রাজবাড়ী সদর', 'url' => 'sadar.rajbari.gov.bd'),
            array('district_slug' => 'rajbari', 'name' => 'Goalanda', 'name_bn' => 'গোয়ালন্দ', 'url' => 'goalanda.rajbari.gov.bd'),
            array('district_slug' => 'rajbari', 'name' => 'Pangsa', 'name_bn' => 'পাংশা', 'url' => 'pangsa.rajbari.gov.bd'),
            array('district_slug' => 'rajbari', 'name' => 'Baliakandi', 'name_bn' => 'বালিয়াকান্দি', 'url' => 'baliakandi.rajbari.gov.bd'),
            array('district_slug' => 'rajbari', 'name' => 'Kalukhali', 'name_bn' => 'কালুখালী', 'url' => 'kalukhali.rajbari.gov.bd'),
            array('district_slug' => 'madaripur', 'name' => 'Madaripur Sadar', 'name_bn' => 'মাদারীপুর সদর', 'url' => 'sadar.madaripur.gov.bd'),
            array('district_slug' => 'madaripur', 'name' => 'Shibchar', 'name_bn' => 'শিবচর', 'url' => 'shibchar.madaripur.gov.bd'),
            array('district_slug' => 'madaripur', 'name' => 'Kalkini', 'name_bn' => 'কালকিনি', 'url' => 'kalkini.madaripur.gov.bd'),
            array('district_slug' => 'madaripur', 'name' => 'Rajoir', 'name_bn' => 'রাজৈর', 'url' => 'rajoir.madaripur.gov.bd'),
            array('district_slug' => 'gopalganj', 'name' => 'Gopalganj Sadar', 'name_bn' => 'গোপালগঞ্জ সদর', 'url' => 'sadar.gopalganj.gov.bd'),
            array('district_slug' => 'gopalganj', 'name' => 'Kashiani', 'name_bn' => 'কাশিয়ানী', 'url' => 'kashiani.gopalganj.gov.bd'),
            array('district_slug' => 'gopalganj', 'name' => 'Tungipara', 'name_bn' => 'টুংগীপাড়া', 'url' => 'tungipara.gopalganj.gov.bd'),
            array('district_slug' => 'gopalganj', 'name' => 'Kotalipara', 'name_bn' => 'কোটালীপাড়া', 'url' => 'kotalipara.gopalganj.gov.bd'),
            array('district_slug' => 'gopalganj', 'name' => 'Muksudpur', 'name_bn' => 'মুকসুদপুর', 'url' => 'muksudpur.gopalganj.gov.bd'),
            array('district_slug' => 'faridpur', 'name' => 'Faridpur Sadar', 'name_bn' => 'ফরিদপুর সদর', 'url' => 'sadar.faridpur.gov.bd'),
            array('district_slug' => 'faridpur', 'name' => 'Alfadanga', 'name_bn' => 'আলফাডাঙ্গা', 'url' => 'alfadanga.faridpur.gov.bd'),
            array('district_slug' => 'faridpur', 'name' => 'Boalmari', 'name_bn' => 'বোয়ালমারী', 'url' => 'boalmari.faridpur.gov.bd'),
            array('district_slug' => 'faridpur', 'name' => 'Sadarpur', 'name_bn' => 'সদরপুর', 'url' => 'sadarpur.faridpur.gov.bd'),
            array('district_slug' => 'faridpur', 'name' => 'Nagarkanda', 'name_bn' => 'নগরকান্দা', 'url' => 'nagarkanda.faridpur.gov.bd'),
            array('district_slug' => 'faridpur', 'name' => 'Bhanga', 'name_bn' => 'ভাঙ্গা', 'url' => 'bhanga.faridpur.gov.bd'),
            array('district_slug' => 'faridpur', 'name' => 'Charbhadrasan', 'name_bn' => 'চরভদ্রাসন', 'url' => 'charbhadrasan.faridpur.gov.bd'),
            array('district_slug' => 'faridpur', 'name' => 'Madhukhali', 'name_bn' => 'মধুখালী', 'url' => 'madhukhali.faridpur.gov.bd'),
            array('district_slug' => 'faridpur', 'name' => 'Saltha', 'name_bn' => 'সালথা', 'url' => 'saltha.faridpur.gov.bd'),
            array('district_slug' => 'panchagarh', 'name' => 'Panchagarh Sadar', 'name_bn' => 'পঞ্চগড় সদর', 'url' => 'panchagarhsadar.panchagarh.gov.bd'),
            array('district_slug' => 'panchagarh', 'name' => 'Debiganj', 'name_bn' => 'দেবীগঞ্জ', 'url' => 'debiganj.panchagarh.gov.bd'),
            array('district_slug' => 'panchagarh', 'name' => 'Boda', 'name_bn' => 'বোদা', 'url' => 'boda.panchagarh.gov.bd'),
            array('district_slug' => 'panchagarh', 'name' => 'Atwari', 'name_bn' => 'আটোয়ারী', 'url' => 'atwari.panchagarh.gov.bd'),
            array('district_slug' => 'panchagarh', 'name' => 'Tetulia', 'name_bn' => 'তেতুলিয়া', 'url' => 'tetulia.panchagarh.gov.bd'),
            array('district_slug' => 'dinajpur', 'name' => 'Nawabganj', 'name_bn' => 'নবাবগঞ্জ', 'url' => 'nawabganj.dinajpur.gov.bd'),
            array('district_slug' => 'dinajpur', 'name' => 'Birganj', 'name_bn' => 'বীরগঞ্জ', 'url' => 'birganj.dinajpur.gov.bd'),
            array('district_slug' => 'dinajpur', 'name' => 'Ghoraghat', 'name_bn' => 'ঘোড়াঘাট', 'url' => 'ghoraghat.dinajpur.gov.bd'),
            array('district_slug' => 'dinajpur', 'name' => 'Birampur', 'name_bn' => 'বিরামপুর', 'url' => 'birampur.dinajpur.gov.bd'),
            array('district_slug' => 'dinajpur', 'name' => 'Parbatipur', 'name_bn' => 'পার্বতীপুর', 'url' => 'parbatipur.dinajpur.gov.bd'),
            array('district_slug' => 'dinajpur', 'name' => 'Bochaganj', 'name_bn' => 'বোচাগঞ্জ', 'url' => 'bochaganj.dinajpur.gov.bd'),
            array('district_slug' => 'dinajpur', 'name' => 'Kaharol', 'name_bn' => 'কাহারোল', 'url' => 'kaharol.dinajpur.gov.bd'),
            array('district_slug' => 'dinajpur', 'name' => 'Fulbari', 'name_bn' => 'ফুলবাড়ী', 'url' => 'fulbari.dinajpur.gov.bd'),
            array('district_slug' => 'dinajpur', 'name' => 'Dinajpur Sadar', 'name_bn' => 'দিনাজপুর সদর', 'url' => 'dinajpursadar.dinajpur.gov.bd'),
            array('district_slug' => 'dinajpur', 'name' => 'Hakimpur', 'name_bn' => 'হাকিমপুর', 'url' => 'hakimpur.dinajpur.gov.bd'),
            array('district_slug' => 'dinajpur', 'name' => 'Khansama', 'name_bn' => 'খানসামা', 'url' => 'khansama.dinajpur.gov.bd'),
            array('district_slug' => 'dinajpur', 'name' => 'Birol', 'name_bn' => 'বিরল', 'url' => 'birol.dinajpur.gov.bd'),
            array('district_slug' => 'dinajpur', 'name' => 'Chirirbandar', 'name_bn' => 'চিরিরবন্দর', 'url' => 'chirirbandar.dinajpur.gov.bd'),
            array('district_slug' => 'lalmonirhat', 'name' => 'Lalmonirhat Sadar', 'name_bn' => 'লালমনিরহাট সদর', 'url' => 'sadar.lalmonirhat.gov.bd'),
            array('district_slug' => 'lalmonirhat', 'name' => 'Kaliganj', 'name_bn' => 'কালীগঞ্জ', 'url' => 'kaliganj.lalmonirhat.gov.bd'),
            array('district_slug' => 'lalmonirhat', 'name' => 'Hatibandha', 'name_bn' => 'হাতীবান্ধা', 'url' => 'hatibandha.lalmonirhat.gov.bd'),
            array('district_slug' => 'lalmonirhat', 'name' => 'Patgram', 'name_bn' => 'পাটগ্রাম', 'url' => 'patgram.lalmonirhat.gov.bd'),
            array('district_slug' => 'lalmonirhat', 'name' => 'Aditmari', 'name_bn' => 'আদিতমারী', 'url' => 'aditmari.lalmonirhat.gov.bd'),
            array('district_slug' => 'nilphamari', 'name' => 'Syedpur', 'name_bn' => 'সৈয়দপুর', 'url' => 'syedpur.nilphamari.gov.bd'),
            array('district_slug' => 'nilphamari', 'name' => 'Domar', 'name_bn' => 'ডোমার', 'url' => 'domar.nilphamari.gov.bd'),
            array('district_slug' => 'nilphamari', 'name' => 'Dimla', 'name_bn' => 'ডিমলা', 'url' => 'dimla.nilphamari.gov.bd'),
            array('district_slug' => 'nilphamari', 'name' => 'Jaldhaka', 'name_bn' => 'জলঢাকা', 'url' => 'jaldhaka.nilphamari.gov.bd'),
            array('district_slug' => 'nilphamari', 'name' => 'Kishorganj', 'name_bn' => 'কিশোরগঞ্জ', 'url' => 'kishorganj.nilphamari.gov.bd'),
            array('district_slug' => 'nilphamari', 'name' => 'Nilphamari Sadar', 'name_bn' => 'নীলফামারী সদর', 'url' => 'nilphamarisadar.nilphamari.gov.bd'),
            array('district_slug' => 'gaibandha', 'name' => 'Sadullapur', 'name_bn' => 'সাদুল্লাপুর', 'url' => 'sadullapur.gaibandha.gov.bd'),
            array('district_slug' => 'gaibandha', 'name' => 'Gaibandha Sadar', 'name_bn' => 'গাইবান্ধা সদর', 'url' => 'gaibandhasadar.gaibandha.gov.bd'),
            array('district_slug' => 'gaibandha', 'name' => 'Palashbari', 'name_bn' => 'পলাশবাড়ী', 'url' => 'palashbari.gaibandha.gov.bd'),
            array('district_slug' => 'gaibandha', 'name' => 'Saghata', 'name_bn' => 'সাঘাটা', 'url' => 'saghata.gaibandha.gov.bd'),
            array('district_slug' => 'gaibandha', 'name' => 'Gobindaganj', 'name_bn' => 'গোবিন্দগঞ্জ', 'url' => 'gobindaganj.gaibandha.gov.bd'),
            array('district_slug' => 'gaibandha', 'name' => 'Sundarganj', 'name_bn' => 'সুন্দরগঞ্জ', 'url' => 'sundarganj.gaibandha.gov.bd'),
            array('district_slug' => 'gaibandha', 'name' => 'Phulchari', 'name_bn' => 'ফুলছড়ি', 'url' => 'phulchari.gaibandha.gov.bd'),
            array('district_slug' => 'thakurgaon', 'name' => 'Thakurgaon Sadar', 'name_bn' => 'ঠাকুরগাঁও সদর', 'url' => 'thakurgaonsadar.thakurgaon.gov.bd'),
            array('district_slug' => 'thakurgaon', 'name' => 'Pirganj', 'name_bn' => 'পীরগঞ্জ', 'url' => 'pirganj.thakurgaon.gov.bd'),
            array('district_slug' => 'thakurgaon', 'name' => 'Ranisankail', 'name_bn' => 'রাণীশংকৈল', 'url' => 'ranisankail.thakurgaon.gov.bd'),
            array('district_slug' => 'thakurgaon', 'name' => 'Haripur', 'name_bn' => 'হরিপুর', 'url' => 'haripur.thakurgaon.gov.bd'),
            array('district_slug' => 'thakurgaon', 'name' => 'Baliadangi', 'name_bn' => 'বালিয়াডাঙ্গী', 'url' => 'baliadangi.thakurgaon.gov.bd'),
            array('district_slug' => 'rangpur', 'name' => 'Rangpur Sadar', 'name_bn' => 'রংপুর সদর', 'url' => 'rangpursadar.rangpur.gov.bd'),
            array('district_slug' => 'rangpur', 'name' => 'Gangachara', 'name_bn' => 'গংগাচড়া', 'url' => 'gangachara.rangpur.gov.bd'),
            array('district_slug' => 'rangpur', 'name' => 'Taragonj', 'name_bn' => 'তারাগঞ্জ', 'url' => 'taragonj.rangpur.gov.bd'),
            array('district_slug' => 'rangpur', 'name' => 'Badargonj', 'name_bn' => 'বদরগঞ্জ', 'url' => 'badargonj.rangpur.gov.bd'),
            array('district_slug' => 'rangpur', 'name' => 'Mithapukur', 'name_bn' => 'মিঠাপুকুর', 'url' => 'mithapukur.rangpur.gov.bd'),
            array('district_slug' => 'rangpur', 'name' => 'Pirgonj', 'name_bn' => 'পীরগঞ্জ', 'url' => 'pirgonj.rangpur.gov.bd'),
            array('district_slug' => 'rangpur', 'name' => 'Kaunia', 'name_bn' => 'কাউনিয়া', 'url' => 'kaunia.rangpur.gov.bd'),
            array('district_slug' => 'rangpur', 'name' => 'Pirgacha', 'name_bn' => 'পীরগাছা', 'url' => 'pirgacha.rangpur.gov.bd'),
            array('district_slug' => 'kurigram', 'name' => 'Kurigram Sadar', 'name_bn' => 'কুড়িগ্রাম সদর', 'url' => 'kurigramsadar.kurigram.gov.bd'),
            array('district_slug' => 'kurigram', 'name' => 'Nageshwari', 'name_bn' => 'নাগেশ্বরী', 'url' => 'nageshwari.kurigram.gov.bd'),
            array('district_slug' => 'kurigram', 'name' => 'Bhurungamari', 'name_bn' => 'ভুরুঙ্গামারী', 'url' => 'bhurungamari.kurigram.gov.bd'),
            array('district_slug' => 'kurigram', 'name' => 'Phulbari', 'name_bn' => 'ফুলবাড়ী', 'url' => 'phulbari.kurigram.gov.bd'),
            array('district_slug' => 'kurigram', 'name' => 'Rajarhat', 'name_bn' => 'রাজারহাট', 'url' => 'rajarhat.kurigram.gov.bd'),
            array('district_slug' => 'kurigram', 'name' => 'Ulipur', 'name_bn' => 'উলিপুর', 'url' => 'ulipur.kurigram.gov.bd'),
            array('district_slug' => 'kurigram', 'name' => 'Chilmari', 'name_bn' => 'চিলমারী', 'url' => 'chilmari.kurigram.gov.bd'),
            array('district_slug' => 'kurigram', 'name' => 'Rowmari', 'name_bn' => 'রৌমারী', 'url' => 'rowmari.kurigram.gov.bd'),
            array('district_slug' => 'kurigram', 'name' => 'Charrajibpur', 'name_bn' => 'চর রাজিবপুর', 'url' => 'charrajibpur.kurigram.gov.bd'),
            array('district_slug' => 'sherpur', 'name' => 'Sherpur Sadar', 'name_bn' => 'শেরপুর সদর', 'url' => 'sherpursadar.sherpur.gov.bd'),
            array('district_slug' => 'sherpur', 'name' => 'Nalitabari', 'name_bn' => 'নালিতাবাড়ী', 'url' => 'nalitabari.sherpur.gov.bd'),
            array('district_slug' => 'sherpur', 'name' => 'Sreebordi', 'name_bn' => 'শ্রীবরদী', 'url' => 'sreebordi.sherpur.gov.bd'),
            array('district_slug' => 'sherpur', 'name' => 'Nokla', 'name_bn' => 'নকলা', 'url' => 'nokla.sherpur.gov.bd'),
            array('district_slug' => 'sherpur', 'name' => 'Jhenaigati', 'name_bn' => 'ঝিনাইগাতী', 'url' => 'jhenaigati.sherpur.gov.bd'),
            array('district_slug' => 'mymensingh', 'name' => 'Fulbaria', 'name_bn' => 'ফুলবাড়ীয়া', 'url' => 'fulbaria.mymensingh.gov.bd'),
            array('district_slug' => 'mymensingh', 'name' => 'Trishal', 'name_bn' => 'ত্রিশাল', 'url' => 'trishal.mymensingh.gov.bd'),
            array('district_slug' => 'mymensingh', 'name' => 'Bhaluka', 'name_bn' => 'ভালুকা', 'url' => 'bhaluka.mymensingh.gov.bd'),
            array('district_slug' => 'mymensingh', 'name' => 'Muktagacha', 'name_bn' => 'মুক্তাগাছা', 'url' => 'muktagacha.mymensingh.gov.bd'),
            array('district_slug' => 'mymensingh', 'name' => 'Mymensingh Sadar', 'name_bn' => 'ময়মনসিংহ সদর', 'url' => 'mymensinghsadar.mymensingh.gov.bd'),
            array('district_slug' => 'mymensingh', 'name' => 'Dhobaura', 'name_bn' => 'ধোবাউড়া', 'url' => 'dhobaura.mymensingh.gov.bd'),
            array('district_slug' => 'mymensingh', 'name' => 'Phulpur', 'name_bn' => 'ফুলপুর', 'url' => 'phulpur.mymensingh.gov.bd'),
            array('district_slug' => 'mymensingh', 'name' => 'Haluaghat', 'name_bn' => 'হালুয়াঘাট', 'url' => 'haluaghat.mymensingh.gov.bd'),
            array('district_slug' => 'mymensingh', 'name' => 'Gouripur', 'name_bn' => 'গৌরীপুর', 'url' => 'gouripur.mymensingh.gov.bd'),
            array('district_slug' => 'mymensingh', 'name' => 'Gafargaon', 'name_bn' => 'গফরগাঁও', 'url' => 'gafargaon.mymensingh.gov.bd'),
            array('district_slug' => 'mymensingh', 'name' => 'Iswarganj', 'name_bn' => 'ঈশ্বরগঞ্জ', 'url' => 'iswarganj.mymensingh.gov.bd'),
            array('district_slug' => 'mymensingh', 'name' => 'Nandail', 'name_bn' => 'নান্দাইল', 'url' => 'nandail.mymensingh.gov.bd'),
            array('district_slug' => 'mymensingh', 'name' => 'Tarakanda', 'name_bn' => 'তারাকান্দা', 'url' => 'tarakanda.mymensingh.gov.bd'),
            array('district_slug' => 'jamalpur', 'name' => 'Jamalpur Sadar', 'name_bn' => 'জামালপুর সদর', 'url' => 'jamalpursadar.jamalpur.gov.bd'),
            array('district_slug' => 'jamalpur', 'name' => 'Melandah', 'name_bn' => 'মেলান্দহ', 'url' => 'melandah.jamalpur.gov.bd'),
            array('district_slug' => 'jamalpur', 'name' => 'Islampur', 'name_bn' => 'ইসলামপুর', 'url' => 'islampur.jamalpur.gov.bd'),
            array('district_slug' => 'jamalpur', 'name' => 'Dewangonj', 'name_bn' => 'দেওয়ানগঞ্জ', 'url' => 'dewangonj.jamalpur.gov.bd'),
            array('district_slug' => 'jamalpur', 'name' => 'Sarishabari', 'name_bn' => 'সরিষাবাড়ী', 'url' => 'sarishabari.jamalpur.gov.bd'),
            array('district_slug' => 'jamalpur', 'name' => 'Madarganj', 'name_bn' => 'মাদারগঞ্জ', 'url' => 'madarganj.jamalpur.gov.bd'),
            array('district_slug' => 'jamalpur', 'name' => 'Bokshiganj', 'name_bn' => 'বকশীগঞ্জ', 'url' => 'bokshiganj.jamalpur.gov.bd'),
            array('district_slug' => 'netrokona', 'name' => 'Barhatta', 'name_bn' => 'বারহাট্টা', 'url' => 'barhatta.netrokona.gov.bd'),
            array('district_slug' => 'netrokona', 'name' => 'Durgapur', 'name_bn' => 'দুর্গাপুর', 'url' => 'durgapur.netrokona.gov.bd'),
            array('district_slug' => 'netrokona', 'name' => 'Kendua', 'name_bn' => 'কেন্দুয়া', 'url' => 'kendua.netrokona.gov.bd'),
            array('district_slug' => 'netrokona', 'name' => 'Atpara', 'name_bn' => 'আটপাড়া', 'url' => 'atpara.netrokona.gov.bd'),
            array('district_slug' => 'netrokona', 'name' => 'Madan', 'name_bn' => 'মদন', 'url' => 'madan.netrokona.gov.bd'),
            array('district_slug' => 'netrokona', 'name' => 'Khaliajuri', 'name_bn' => 'খালিয়াজুরী', 'url' => 'khaliajuri.netrokona.gov.bd'),
            array('district_slug' => 'netrokona', 'name' => 'Kalmakanda', 'name_bn' => 'কলমাকান্দা', 'url' => 'kalmakanda.netrokona.gov.bd'),
            array('district_slug' => 'netrokona', 'name' => 'Mohongonj', 'name_bn' => 'মোহনগঞ্জ', 'url' => 'mohongonj.netrokona.gov.bd'),
            array('district_slug' => 'netrokona', 'name' => 'Purbadhala', 'name_bn' => 'পূর্বধলা', 'url' => 'purbadhala.netrokona.gov.bd'),
            array('district_slug' => 'netrokona', 'name' => 'Netrokona Sadar', 'name_bn' => 'নেত্রকোণা সদর', 'url' => 'netrokonasadar.netrokona.gov.bd'),
        );

        foreach ($upazilas as $upazila) {

            $district = District::where('slug', $upazila['district_slug'])->first();

            Thana::create([
                'district_id' => $district->id,
                'name' => $upazila['name'],
                'bn_name' => $upazila['name_bn'],
                'url' => $upazila['url'],
                'slug' => Str::slug($upazila['name']),
                'status' => 1
            ]);
        }
    }
}
